apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-backend
  namespace: NAMESPACE
  labels:
    app: APP_NAME
    component: backend
spec:
  type: ClusterIP
  selector:
    app: APP_NAME
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
